# -*- coding: utf-8 -*-
"""pdf_summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bp0sWI7Q5wV_Vb1afWWJGk3MQWMrP7dw
"""

!pip install transformers pypdf2 sentencepiece

import PyPDF2

from google.colab import files

uploaded= files.upload()

p_text = ""
for f_n in uploaded.keys():
    with open(f_n, "rb") as f:
        reader = PyPDF2.PdfReader(f)
        for page in reader.pages:
            p_text += page.extract_text()

from transformers import pipeline

s_m_r = pipeline("summarization", model="facebook/bart-large-cnn")

def split_t(txt, max_tokens=512):
    import textwrap
    return textwrap.wrap(txt, max_tokens)

chnks = split_t(p_text)

summary = ""
chunk_num = 1

for cnk in chnks:
    print(f"Processing chunk {chunk_num}/{len(chnks)}...")
    inp_len = len(cnk.split())
    max_len = int(inp_len * 0.5)
    max_len = min(max_len, 130)
    rsl = s_m_r(cnk, max_length=max_len, min_length=30, do_sample=False)
    summary += rsl[0]['summary_text'] + " "
    chunk_num += 1

print("Summary of the PDF:")
print(summary)